#pragma once

/// @file
/// @brief Umbrella include for the RHI module. Pulls in every public header.

#include "Platform/RHIPlatform.h"
#include "RHIAdapter.h"
#include "RHIBarrier.h"
#include "RHIBuffer.h"
#include "RHICommandList.h"
#include "RHIDebug.h"
#include "RHIDescriptor.h"
#include "RHIDevice.h"
#include "RHIEnums.h"
#include "RHIFeatures.h"
#include "RHIFormat.h"
#include "RHIForward.h"
#include "RHIHandle.h"
#include "RHIInstance.h"
#include "RHIMemory.h"
#include "RHIMeshShading.h"
#include "RHINativeHandle.h"
#include "RHIPipeline.h"
#include "RHIQuery.h"
#include "RHIQueue.h"
#include "RHIRayTracing.h"
#include "RHIResource.h"
#include "RHISampler.h"
#include "RHIShader.h"
#include "RHIStructChain.h"
#include "RHISwapChain.h"
#include "RHISync.h"
#include "RHITexture.h"
#include "RHIWorkGraph.h"
