/// @file
/// @brief RhiFormat → DXGI_FORMAT tables.

#include "D3D12FormatTable.h"

namespace goleta::rhi::d3d12
{
namespace
{

struct FormatEntry
{
    DXGI_FORMAT Typed;
    DXGI_FORMAT Srv;
    DXGI_FORMAT Dsv;
    DXGI_FORMAT Typeless;
};

constexpr FormatEntry kTable[] = {
    // Unknown
    {DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_UNKNOWN},

    {DXGI_FORMAT_R8_UNORM,      DXGI_FORMAT_R8_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8_TYPELESS},
    {DXGI_FORMAT_R8_SNORM,      DXGI_FORMAT_R8_SNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8_TYPELESS},
    {DXGI_FORMAT_R8_UINT,       DXGI_FORMAT_R8_UINT,       DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8_TYPELESS},
    {DXGI_FORMAT_R8_SINT,       DXGI_FORMAT_R8_SINT,       DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8_TYPELESS},

    {DXGI_FORMAT_R8G8_UNORM,    DXGI_FORMAT_R8G8_UNORM,    DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8_TYPELESS},
    {DXGI_FORMAT_R8G8_SNORM,    DXGI_FORMAT_R8G8_SNORM,    DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8_TYPELESS},
    {DXGI_FORMAT_R8G8_UINT,     DXGI_FORMAT_R8G8_UINT,     DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8_TYPELESS},
    {DXGI_FORMAT_R8G8_SINT,     DXGI_FORMAT_R8G8_SINT,     DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8_TYPELESS},

    {DXGI_FORMAT_R8G8B8A8_UNORM,      DXGI_FORMAT_R8G8B8A8_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8B8A8_TYPELESS},
    {DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, DXGI_FORMAT_R8G8B8A8_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8B8A8_TYPELESS},
    {DXGI_FORMAT_R8G8B8A8_SNORM,      DXGI_FORMAT_R8G8B8A8_SNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8B8A8_TYPELESS},
    {DXGI_FORMAT_R8G8B8A8_UINT,       DXGI_FORMAT_R8G8B8A8_UINT,       DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8B8A8_TYPELESS},
    {DXGI_FORMAT_R8G8B8A8_SINT,       DXGI_FORMAT_R8G8B8A8_SINT,       DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R8G8B8A8_TYPELESS},
    {DXGI_FORMAT_B8G8R8A8_UNORM,      DXGI_FORMAT_B8G8R8A8_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_B8G8R8A8_TYPELESS},
    {DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, DXGI_FORMAT_B8G8R8A8_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_B8G8R8A8_TYPELESS},

    {DXGI_FORMAT_R16_UNORM, DXGI_FORMAT_R16_UNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_TYPELESS},
    {DXGI_FORMAT_R16_SNORM, DXGI_FORMAT_R16_SNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_TYPELESS},
    {DXGI_FORMAT_R16_UINT,  DXGI_FORMAT_R16_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_TYPELESS},
    {DXGI_FORMAT_R16_SINT,  DXGI_FORMAT_R16_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_TYPELESS},
    {DXGI_FORMAT_R16_FLOAT, DXGI_FORMAT_R16_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16_TYPELESS},

    {DXGI_FORMAT_R16G16_UNORM, DXGI_FORMAT_R16G16_UNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16_TYPELESS},
    {DXGI_FORMAT_R16G16_SNORM, DXGI_FORMAT_R16G16_SNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16_TYPELESS},
    {DXGI_FORMAT_R16G16_UINT,  DXGI_FORMAT_R16G16_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16_TYPELESS},
    {DXGI_FORMAT_R16G16_SINT,  DXGI_FORMAT_R16G16_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16_TYPELESS},
    {DXGI_FORMAT_R16G16_FLOAT, DXGI_FORMAT_R16G16_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16_TYPELESS},

    {DXGI_FORMAT_R16G16B16A16_UNORM, DXGI_FORMAT_R16G16B16A16_UNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16B16A16_TYPELESS},
    {DXGI_FORMAT_R16G16B16A16_SNORM, DXGI_FORMAT_R16G16B16A16_SNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16B16A16_TYPELESS},
    {DXGI_FORMAT_R16G16B16A16_UINT,  DXGI_FORMAT_R16G16B16A16_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16B16A16_TYPELESS},
    {DXGI_FORMAT_R16G16B16A16_SINT,  DXGI_FORMAT_R16G16B16A16_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16B16A16_TYPELESS},
    {DXGI_FORMAT_R16G16B16A16_FLOAT, DXGI_FORMAT_R16G16B16A16_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R16G16B16A16_TYPELESS},

    {DXGI_FORMAT_R32_UINT,  DXGI_FORMAT_R32_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32_TYPELESS},
    {DXGI_FORMAT_R32_SINT,  DXGI_FORMAT_R32_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32_TYPELESS},
    {DXGI_FORMAT_R32_FLOAT, DXGI_FORMAT_R32_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32_TYPELESS},

    {DXGI_FORMAT_R32G32_UINT,  DXGI_FORMAT_R32G32_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32_TYPELESS},
    {DXGI_FORMAT_R32G32_SINT,  DXGI_FORMAT_R32G32_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32_TYPELESS},
    {DXGI_FORMAT_R32G32_FLOAT, DXGI_FORMAT_R32G32_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32_TYPELESS},

    {DXGI_FORMAT_R32G32B32_UINT,  DXGI_FORMAT_R32G32B32_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32B32_TYPELESS},
    {DXGI_FORMAT_R32G32B32_SINT,  DXGI_FORMAT_R32G32B32_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32B32_TYPELESS},
    {DXGI_FORMAT_R32G32B32_FLOAT, DXGI_FORMAT_R32G32B32_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32B32_TYPELESS},

    {DXGI_FORMAT_R32G32B32A32_UINT,  DXGI_FORMAT_R32G32B32A32_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32B32A32_TYPELESS},
    {DXGI_FORMAT_R32G32B32A32_SINT,  DXGI_FORMAT_R32G32B32A32_SINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32B32A32_TYPELESS},
    {DXGI_FORMAT_R32G32B32A32_FLOAT, DXGI_FORMAT_R32G32B32A32_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R32G32B32A32_TYPELESS},

    {DXGI_FORMAT_R11G11B10_FLOAT, DXGI_FORMAT_R11G11B10_FLOAT, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R11G11B10_FLOAT},
    {DXGI_FORMAT_R10G10B10A2_UNORM, DXGI_FORMAT_R10G10B10A2_UNORM, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R10G10B10A2_TYPELESS},
    {DXGI_FORMAT_R10G10B10A2_UINT,  DXGI_FORMAT_R10G10B10A2_UINT,  DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R10G10B10A2_TYPELESS},
    {DXGI_FORMAT_R9G9B9E5_SHAREDEXP, DXGI_FORMAT_R9G9B9E5_SHAREDEXP, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_R9G9B9E5_SHAREDEXP},

    // Depth formats: the resource is created Typeless so the texture can also expose an SRV.
    {DXGI_FORMAT_D16_UNORM,         DXGI_FORMAT_R16_UNORM,              DXGI_FORMAT_D16_UNORM,         DXGI_FORMAT_R16_TYPELESS},
    {DXGI_FORMAT_D24_UNORM_S8_UINT, DXGI_FORMAT_R24_UNORM_X8_TYPELESS,  DXGI_FORMAT_D24_UNORM_S8_UINT, DXGI_FORMAT_R24G8_TYPELESS},
    {DXGI_FORMAT_D32_FLOAT,         DXGI_FORMAT_R32_FLOAT,              DXGI_FORMAT_D32_FLOAT,         DXGI_FORMAT_R32_TYPELESS},
    {DXGI_FORMAT_D32_FLOAT_S8X24_UINT, DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS, DXGI_FORMAT_D32_FLOAT_S8X24_UINT, DXGI_FORMAT_R32G8X24_TYPELESS},

    // BC formats.
    {DXGI_FORMAT_BC1_UNORM,      DXGI_FORMAT_BC1_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC1_TYPELESS},
    {DXGI_FORMAT_BC1_UNORM_SRGB, DXGI_FORMAT_BC1_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC1_TYPELESS},
    {DXGI_FORMAT_BC1_UNORM,      DXGI_FORMAT_BC1_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC1_TYPELESS},
    {DXGI_FORMAT_BC1_UNORM_SRGB, DXGI_FORMAT_BC1_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC1_TYPELESS},
    {DXGI_FORMAT_BC2_UNORM,      DXGI_FORMAT_BC2_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC2_TYPELESS},
    {DXGI_FORMAT_BC2_UNORM_SRGB, DXGI_FORMAT_BC2_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC2_TYPELESS},
    {DXGI_FORMAT_BC3_UNORM,      DXGI_FORMAT_BC3_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC3_TYPELESS},
    {DXGI_FORMAT_BC3_UNORM_SRGB, DXGI_FORMAT_BC3_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC3_TYPELESS},
    {DXGI_FORMAT_BC4_UNORM,      DXGI_FORMAT_BC4_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC4_TYPELESS},
    {DXGI_FORMAT_BC4_SNORM,      DXGI_FORMAT_BC4_SNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC4_TYPELESS},
    {DXGI_FORMAT_BC5_UNORM,      DXGI_FORMAT_BC5_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC5_TYPELESS},
    {DXGI_FORMAT_BC5_SNORM,      DXGI_FORMAT_BC5_SNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC5_TYPELESS},
    {DXGI_FORMAT_BC6H_UF16,      DXGI_FORMAT_BC6H_UF16,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC6H_TYPELESS},
    {DXGI_FORMAT_BC6H_SF16,      DXGI_FORMAT_BC6H_SF16,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC6H_TYPELESS},
    {DXGI_FORMAT_BC7_UNORM,      DXGI_FORMAT_BC7_UNORM,      DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC7_TYPELESS},
    {DXGI_FORMAT_BC7_UNORM_SRGB, DXGI_FORMAT_BC7_UNORM_SRGB, DXGI_FORMAT_UNKNOWN, DXGI_FORMAT_BC7_TYPELESS},
};

static_assert(sizeof(kTable) / sizeof(kTable[0]) == static_cast<size_t>(RhiFormat::Count),
              "D3D12 format table must mirror RhiFormat one-for-one");

inline const FormatEntry& entry(RhiFormat Format) noexcept
{
    const auto Idx = static_cast<size_t>(Format);
    if (Idx >= static_cast<size_t>(RhiFormat::Count))
        return kTable[0];
    return kTable[Idx];
}

} // namespace

DXGI_FORMAT toDxgi(RhiFormat Format) noexcept         { return entry(Format).Typed; }
DXGI_FORMAT toDxgiSrv(RhiFormat Format) noexcept      { return entry(Format).Srv; }
DXGI_FORMAT toDxgiDsv(RhiFormat Format) noexcept      { return entry(Format).Dsv; }
DXGI_FORMAT toDxgiTypeless(RhiFormat Format) noexcept { return entry(Format).Typeless; }

} // namespace goleta::rhi::d3d12
